GOF-45, added redux
nerived/gof-bomberman-game pull request #14
Opened 2024-02-29 21:40 UTC by nerived

### Какую задачу решаем
Добавлен redux, слайс пользователя и обновление сброс при логине и разлогине.
Добавил временную логику логина, т.к. не известно какую часть работ реализовала Вика для форм. 

Так же можно встретить местами any и ts-ignore, т.к. нам нельзя санки как либу использовать, то пока с типизацией проблемы. По факту если дружить с ts надо просто копипастить либу. Но там и так понятно что там вся магия твориться проверкой на функцию.

2024-03-01 07:33 UTC, MikePortnoy1985 commented on packages/client/src/pages/Login/LoginPage.tsx
> +      | null = e.nativeEvent.target
а зачем nativeEvent использовать? почему не просто event.target

2024-03-01 07:35 UTC, MikePortnoy1985 approved these changes

2024-03-01 07:52 UTC, nerived commented on packages/client/src/pages/Login/LoginPage.tsx
> +      | null = e.nativeEvent.target
Да, можно и в event.target, поменял.

2024-03-01 10:51 UTC, eprikhodko approved these changes

2024-03-01 18:51 UTC, IvanPeleshok requested changes
Добрый день!

Отлично постарались!
Есть замечания, предлагаю доработать!

Хорошего дня :)

2024-03-01 18:51 UTC, IvanPeleshok commented on packages/client/src/features/user/reducer.ts
> +      return { ...state, ...action.payload }
В рамках слайсе нет необходимости возращать полный объект состояния, а напрямую мутировать необходимое поле: https://redux-toolkit.js.org/usage/usage-with-typescript#defining-action-contents-with-prepare-callbacks

Предлагаю поправить

2024-03-01 18:51 UTC, IvanPeleshok commented on packages/client/src/features/user/thunks.ts
> +export const userLogin = (data: SigninData): any => {
Предлагаю воспользовать createAsyncThunk https://redux-toolkit.js.org/api/createAsyncThunk
Пример
```
const updateUser = createAsyncThunk(
  'users/update',
  async (userData, { rejectWithValue }) => {
    const { id, ...fields } = userData
    try {
      const response = await userAPI.updateById(id, fields)
      return response.data.user
    } catch (err) {
      // Use `err.response.data` as `action.payload` for a `rejected` action,
      // by explicitly returning it using the `rejectWithValue()` utility
      return rejectWithValue(err.response.data)
    }
  },
)

2024-03-01 18:51 UTC, IvanPeleshok commented on packages/client/src/helpers/customThunk.ts
> +const createCustomThunkMiddleware = () => {
При использовании `createAsyncThunk` нет необходимости в кастомной прокладке
Она будет в использоваться в getDefaultMiddleware (вроде, надо уточнить в доке)

2024-03-01 18:51 UTC, IvanPeleshok commented on packages/client/src/pages/Login/LoginPage.tsx
> +//test user
Неиспользуемые данные предлагаю вынести в соответствующие мок файлы для тестов, либо удалить

2024-03-01 18:51 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/Profile.tsx
> +const mapUserField = (user: RootState['user']) => {
Предлагаю вынести в helper декомпозировав логику

2024-03-01 18:51 UTC, IvanPeleshok commented on packages/client/src/pages/Profile/Profile.tsx
>  const userFields = [
По-хорошему, вынести в мок файл

2024-03-01 18:51 UTC, IvanPeleshok commented on packages/client/src/store/index.ts
> +  //@ts-ignore
Для чего игнорировать?

Предлагаю подумать с командой, как можно избежать данного подхода

2024-03-01 18:51 UTC, IvanPeleshok commented on packages/client/src/features/user/reducer.ts
> +    updateUser: (state, action: PayloadAction<User>) => {
Супер, что типизируете :)

2024-03-02 08:16 UTC, nerived commented on packages/client/src/pages/Profile/Profile.tsx
>  const userFields = [
Это не мок респонса,  а мапка для отрисовки ui полей простым проходом map по ним, с простановкой лейбла, key для выборки данных с объекта игрока, и value как дефолтное значение. Вынес в константы.

2024-03-02 08:17 UTC, nerived commented on packages/client/src/store/index.ts
> +  //@ts-ignore
//@ts-ignore самоликвидировался благодаря createAsyncThunk

2024-03-02 19:07 UTC, IvanPeleshok approved these changes
Отлично потрудилсь!
Получилось замечательно :)
Буду рад проверить вашу работу в дальнейшем, а пока апрув 🚀 
Хорошего дня :)

2024-03-02 19:07 UTC, IvanPeleshok commented on packages/client/src/features/user/thunks.ts
> +export const userLogin = async (data: SigninData): Promise<boolean> => {
Не является санкой, можно бы было подумать о переходе на неё :)

2024-03-02 19:07 UTC, IvanPeleshok commented on packages/client/src/features/user/thunks.ts
> +export const userLogout = async () => {
Аналогично

2024-03-02 19:07 UTC, IvanPeleshok commented on packages/client/src/features/user/thunks.ts
> +    if (!error.response) {
```
catch (error) {
if (!error.response) {
  throw error
}
    
return rejectWithValue((error AxiosError<UserError>).response.data)

2024-03-02 19:07 UTC, IvanPeleshok commented on packages/client/src/pages/Login/LoginPage.tsx
> +      dispatch(userThunks.fetchUserThunk())
Запрос может закончиться с ошибкой, было бы здорово обработать данный кейс (рекомендация)

2024-03-02 19:07 UTC, IvanPeleshok commented on packages/client/src/pages/Login/LoginPage.tsx
> +  const handleOnChangeValue = (e: ChangeEvent<HTMLInputElement>) => {
Предлагаю не сокращать наименование переменных, чтобы они были более человекочитаемым `event`

2024-03-03 08:53 UTC, merged