GOF-52: adds OAuth Yandex authorization
nerived/gof-bomberman-game pull request #32
Opened 2024-03-24 14:48 UTC by niksmo

### Какую задачу решаем
Добавить OAuth автризацию с помощью сервиса Яндекса

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-03-25 09:08 UTC, MikePortnoy1985 approved these changes

2024-03-25 18:34 UTC, IvanPeleshok requested changes
Добрый день!

Классно реализовали фичу, но есть пара замечаний

Предлагаю ознакомиться и поправить

Хорошего дня :)

2024-03-25 18:34 UTC, IvanPeleshok commented on packages/client/src/components/OauthYaButton/OauthYaButton.tsx
> +    ).then(data => {
Предлагаю пользоваться async / await для работы с промиссами

Так-же хотелось бы видеть обработку try / catch, если промисс вернёт исключение

2024-03-25 18:34 UTC, IvanPeleshok commented on packages/client/src/components/OauthYaButton/OauthYaButton.tsx
> +  })
Вероятно, что необходимо задать вторым аргументом массив зависимостей, когда useEffect должен вызывать колбек внутри себя https://react.dev/reference/react/useEffect, иначе будет вызываться на каждый реренде

2024-03-26 09:41 UTC, niksmo commented on packages/client/src/components/OauthYaButton/OauthYaButton.tsx
> +  })
Вероятно и не надо ))) от того что он выолнится ничего страшного не произойдёт - для этого там есть проверки. Поставлю пустой массив, чтобы твоё ревью пройти.

2024-03-26 09:43 UTC, niksmo commented on packages/client/src/components/OauthYaButton/OauthYaButton.tsx
> +    ).then(data => {
Прости, но помнится как-то раз мой первый наставник (тим лид из Яндекса), сказал: asyc/await классный сахар, но главное чтобы у вас не было async/await головного мозга, используйте его там где нужно.
Если проми вернёт исключение, редакс его словит - сам попробуй выброси и увидешь, что здесть catch не нужен.

2024-03-26 11:38 UTC, IvanPeleshok commented on packages/client/src/components/OauthYaButton/OauthYaButton.tsx
> +  })
Прозвучало как одолжение :)) (ну тогда спасибо получается 👍 )

Мы же хотим получить на выходе предсказуемый, понятный и человекочитаемый код

Если у меня возникли по этому поводу вопросы, то скорее всего, они должны появится и у других членов команды, поскольку useEffect без второго аргументы используют если никогда, то очень редко

2024-03-26 11:41 UTC, IvanPeleshok commented on packages/client/src/components/OauthYaButton/OauthYaButton.tsx
> +    ).then(data => {
Да, но лучше писать унифицированный код везде

Плюсы использования такого сахара в том, что отлаживать и читать такой код приятнее и проще

Спорить не буду, тимлид из Яндекса глупостей не скажет))

2024-03-26 11:42 UTC, IvanPeleshok approved these changes
Отличная работа
Апрув

Хорошего дня :)

2024-03-26 11:44 UTC, merged