gof-62, added client side support forum API
nerived/gof-bomberman-game pull request #35
Opened 2024-04-01 12:46 UTC by nerived

### Какую задачу решаем
Добавил поддержку будущего Forum API 
Сделал все санки и взаимодейстия с будущим бэком.

Пока отправляют в ревью без рабочего бэка с моками, но в целом все реализовал что требуется. Осталось только методы оживить и моки удалить. 

Фиксы по ревью не смогу сделать после добавления бэка, т.к. буду в отпуске и буду офлайн все время до 12 апреля

2024-04-01 14:51 UTC, MikePortnoy1985 approved these changes

2024-04-02 09:16 UTC, IvanPeleshok requested changes
Отличная работа
Всё сделано красиво и чисто

Есть парочка предложений по улучшению

Предлагаю поправить :)

Хорошего дня 🚀

2024-04-02 09:16 UTC, IvanPeleshok commented on packages/client/src/components/PopupManager/components/CreateTopic/CreateTopic.tsx
> +    if (result.payload) {
Вложенность if-ов не очень хорошая практика, предлагаю переписать на что-то более читаемое:
```
if (result.payload?.isSuccess) {
    const topicId = result.payload?.topicId
    onClosePopup()
    
    if (topicId) {
      navigate(`${RoutesPaths.Forum}/${result.payload.topicId}`)
    }
    
    return
} 
     
if (result.payload?.reason) {
    setErrorMessage(result.payload?.reason)
}

2024-04-02 09:16 UTC, IvanPeleshok commented on packages/client/src/features/forum/thunks/addCommentToTopic.ts
> +    } catch (err) {
Обработка исключений вроде бы везде одинаковая, можно бы было подумать над хелпером, который помог бы решить повторяющийся код (рекомендация)

2024-04-02 09:16 UTC, IvanPeleshok commented on packages/client/src/pages/ForumTopicPage/ForumTopicPage.tsx
> +      dispatch(forumThunks.fetchTopicById(Number(id))).then(() => {
Предлагаю пользоваться везде одним синтаксисом с промиссами, чтобы было унифицировано
async / await + try / catch

2024-04-02 09:16 UTC, IvanPeleshok commented on packages/client/src/pages/ForumTopicPage/ForumTopicPage.tsx
> +    if (result.payload) {
Вложенности if-ов можно избежать

2024-04-02 14:40 UTC, eprikhodko approved these changes

2024-04-03 07:42 UTC, merged